### PR TITLE
Fix permission denied error in discovery service

### LINKED ISSUE #84: Service permission denied
When I try to execute ./discovery it gives this:

```
./run: line 12: ./discovery: Permission denied
```

@felipecrs do you know a solution?

ref: [motioneye](https://github.com/hassio-addons/addon-motioneye/blob/main/motioneye/rootfs/etc/services.d/motioneye/run#L19)

### PR DESCRIPTION
**Pull request by felipecrs**
But this also refactors the whole thing as a S6-Overlay to better take advantage of it.

Closes #84

### CODE REVIEW

File: asterisk/rootfs/etc/services.d/discovery/run [hunk 1]
```diff
@@ -3,22 +3,27 @@
...
+# shellcheck shell=bash
+
+# Wait for Asterisk to become available before continuing
+bashio::net.wait_for 8088
 
 # Create discovery config payload for Home Assistant
 config=$(bashio::var.json \
     host  "127.0.0.1" \
-    port "8089" \
+    port "5038" \
```
Comment (felipecrs) [inline asterisk/rootfs/etc/services.d/discovery/run:15]: @TECH7Fox isn't this the correct port you meant to send?

File: asterisk/rootfs/etc/services.d/discovery/run [hunk 2]
```diff
@@ -3,22 +3,27 @@
...
 # Send Discovery information to Home Assistant
 # ==============================================================================
-declare config
 
-# Wait for motionEye to start before continuing
-bashio::net.wait_for 8089
+# shellcheck shell=bash
+
+# Wait for Asterisk to become available before continuing
+bashio::net.wait_for 8088
```
Comment (felipecrs) [inline asterisk/rootfs/etc/services.d/discovery/run:10]: I think it's more reliable to wait on port 8088, because there would not be any certificate issue.

**Comment by felipecrs** [comment]
image

Is this normal?

File: asterisk/rootfs/etc/services.d/discovery/run (hunk 1 above)
Comment (TECH7Fox) [reply asterisk/rootfs/etc/services.d/discovery/run:15]: It is, thanks.

File: asterisk/rootfs/etc/services.d/discovery/run (hunk 2 above)
Comment (TECH7Fox) [reply asterisk/rootfs/etc/services.d/discovery/run:10]: Good idea.

**Review by TECH7Fox — APPROVED** [review]

**Comment by TECH7Fox** [comment]
> Is this expected?

Think that's the integration side. Will work on that now.
